version: '2'

services:
  prometheus:
    image: docker.io/prom/prometheus
    ports:
      - "9090:9090"
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
  grafana:
    image: docker.io/grafana/grafana:9.0.3
    hostname: grafana
    ports:
      - "3000:3000"
  # java:
  #   image: registry.access.redhat.com/ubi8/openjdk-17