{
 "title": "Java Runtime Statistics",
 "description": "Dashboard for JVM based on JMX exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"jmx_exporter\"},pool)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"jmx_exporter\"},pool)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(java_lang_Runtime_Uptime,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_Uptime{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=~\"$job\", area=\"heap\"}*100/jvm_memory_bytes_max{job=~\"$job\", area=\"heap\"}"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=~\"$job\",area=\"nonheap\"}*100/jvm_memory_bytes_max{job=~\"$job\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"jmx_exporter\"}",
       "legendFormat": "Open Files"
      },
      {
       "expr": "process_max_fds{job=\"jmx_exporter\"}",
       "legendFormat": "Max Files"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=~\"$job\"}*1000"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"jmx_exporter\"}[$__rate_interval])",
       "legendFormat": "System CPU Usage"
      }
     ]
    },
    {
     "title": "Overall Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{job=~\"$job\"})",
       "legendFormat": "Heap + NonHeap"
      },
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\"}",
       "legendFormat": "RSS"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=~\"$job\",pool=~\"$memory_pool_heap\"}",
       "legendFormat": "Used "
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", pool=~\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", pool=~\"$memory_pool_heap\"}",
       "legendFormat": "Max "
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4.8, "x": 0, "y": 10 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=~\"$job\",pool=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\",pool=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{job=~\"$job\",pool=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_currently_loaded{job=~\"$job\"}",
       "legendFormat": "Currently"
      },
      {
       "expr": "jvm_classes_loaded_total{job=~\"$job\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_unloaded_total{job=\"jmx_exporter\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_pool_used_bytes{job=~\"$job\",pool=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_pool_capacity_bytes{job=~\"$job\",pool=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_pool_used_bytes{job=~\"$job\",pool=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_pool_capacity_bytes{job=~\"$job\",pool=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_memory_pool_allocated_bytes_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "allocated"
      },
      {
       "expr": "sum(irate(jvm_memory_pool_promoted_bytes_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon{job=~\"$job\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_current{job=~\"$job\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak{job=~\"$job\"}",
       "legendFormat": "Peak"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}